import subprocess
import pathlib
from dotenv import load_dotenv
import os

from .utils import parse_bool

ENV_FILE = pathlib.Path(__file__).parent.parent / ".platform/.config"
assert ENV_FILE.exists(), f"File not found: {ENV_FILE} (autogenerated by the platform on installation)" # noqa
load_dotenv(dotenv_path=ENV_FILE)

CLUSTER_NAME = os.getenv("CLUSTER_NAME")
assert CLUSTER_NAME is not None
CONTEXT_NAME = f"kind-{CLUSTER_NAME}"

HOST_IP = os.getenv("HOST_IP")
assert HOST_IP is not None

# MLFLOW
MLFLOW_ENV_FILE = pathlib.Path(__file__).parent.parent / "deployment/mlflow/env/local" / "config.env"  # noqa
MLFLOW_SECRETS_FILE = pathlib.Path(__file__).parent.parent / "deployment/mlflow/env/local" / "secret.env"  # noqa

load_dotenv(dotenv_path=MLFLOW_ENV_FILE, override=True)
AWS_ACCESS_KEY_ID = os.getenv("MINIO_ACCESS_KEY")
assert AWS_ACCESS_KEY_ID is not None

load_dotenv(dotenv_path=MLFLOW_SECRETS_FILE, override=True)
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
assert AWS_SECRET_ACCESS_KEY is not None

IS_STANDALONE_KFP = "kfp" in os.environ.get('DEPLOYMENT_OPTION')
SKIP_LOCAL_REGISTRY = not parse_bool(os.environ.get('INSTALL_LOCAL_REGISTRY'))


def pytest_sessionstart(session):
    """
    Called after the Session object has been created and
    before performing collection and entering the run test loop.
    """
    print(f"Set up kubectl context ({CONTEXT_NAME}) before starting the tests.")

    subprocess.run(["kubectl", "config", "use-context", CONTEXT_NAME], stdout=True)
