{
 "title": "Integration Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Last 5 Jobs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cloud_hpc_job_seff_metrics{metric=\"BiUn\"}"
    },
    {
     "expr": "cloud_hpc_job_seff_metrics{metric=\"Nod\"}"
    },
    {
     "expr": "cloud_hpc_job_seff_metrics{metric=\"MemUtiByte\"}"
    },
    {
     "expr": "cloud_hpc_job_seff_metrics{metric=\"MemEffByte\"}"
    }
   ]
  },
  {
   "title": "Pipeline Max Times",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "cloud_hpc_pipeline_time_metrics{group=\"components\"}"
    },
    {
     "expr": "cloud_hpc_pipeline_time_metrics{group=\"ray-jobs\"}"
    }
   ]
  },
  {
   "title": "Pipeline Mean Times",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "cloud_hpc_pipeline_time_metrics{group=\"components\"}"
    },
    {
     "expr": "cloud_hpc_pipeline_time_metrics{group=\"ray-jobs\"}"
    }
   ]
  },
  {
   "title": "Forwarder Max Task Times",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "cloud_hpc_task_time_metrics{collector=\"integration-forwarder-s0-c0-u1\", metric=\"ToTasSec\"}"
    }
   ]
  },
  {
   "title": "Forwarder Mean Task Times",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "cloud_hpc_task_time_metrics{collector=\"integration-forwarder-s0-c0-u1\", metric=\"ToTasSec\"}"
    }
   ]
  },
  {
   "title": "Submitter Max Task Times",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "cloud_hpc_task_time_metrics{collector=\"integration-submitter-s0-c0-u1-user-example-com\"}"
    }
   ]
  },
  {
   "title": "Submitter Max Task Times",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "cloud_hpc_task_time_metrics{collector=\"integration-submitter-s0-c0-u1-user-example-com\"}"
    }
   ]
  }
 ]
}