apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali
  namespace: "istio-system"
  labels:
    helm.sh/chart: kiali-server-2.5.0
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
    version: "v2.5.0"
    app.kubernetes.io/version: "v2.5.0"
    app.kubernetes.io/part-of: "kiali"