{
 "title": "OSS_Monitoring_1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Prometheus Alerts",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Model Performance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "M_Acc" },
    { "expr": "M_TP" },
    { "expr": "M_FP" },
    { "expr": "M_TN" },
    { "expr": "M_FN" }
   ]
  },
  {
   "title": "Dataset Fairness Metrics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Tr_D_DI" },
    { "expr": "Te_D_DI" },
    { "expr": "Tr_D_SP" },
    { "expr": "Te_D_SP" }
   ]
  },
  {
   "title": "Model Fairness Metrics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "M_BA" },
    { "expr": "M_DI" },
    { "expr": "M_SP" },
    { "expr": "M_EOD" },
    { "expr": "M_AOD" },
    { "expr": "M_TI" }
   ]
  },
  {
   "title": "Cluster Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(scaph_process_power_consumption_microwatts{app_kubernetes_io_managed_by=\"Helm\"}) / 1000000"
    }
   ]
  },
  {
   "title": "Energy Consumption of Cluster (1day)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(scaph_process_power_consumption_microwatts{app_kubernetes_io_managed_by=\"Helm\"}[1d])) / (1000000 * 1000 * 24)",
     "legendFormat": "Whole cluster"
    },
    {
     "expr": "sum(sum_over_time(scaph_process_power_consumption_microwatts{app_kubernetes_io_managed_by=\"Helm\", cmdline!~\".*(bin/|app/|conf/|--loglevelinfo|scaphandreprometheus--port8081).*\", exe!~\".*(containerd-shim|nginx|postgres|sleep|workflow-contro|pause|minio|grafana-server|systemd-journal|manager|etcd|kube-apiserver|kube-controller|kube-scheduler|local-path-prov|mysqld|node|persistence_age).*\"}[1d])) / (1000000 * 1000 * 24)",
     "legendFormat": "KFP"
    },
    {
     "expr": "sum(sum_over_time(scaph_process_power_consumption_microwatts{app_kubernetes_io_managed_by=\"Helm\", cmdline =~\".*mlflow.*\"}[1d])) / (1000000 * 1000 * 24)",
     "legendFormat": "MLflow"
    },
    {
     "expr": "sum(sum_over_time(scaph_process_power_consumption_microwatts{app_kubernetes_io_managed_by=\"Helm\", exe=\"prometheus\"}[1d])) / (1000000 * 1000 * 24)",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "sum(sum_over_time(scaph_process_power_consumption_microwatts{app_kubernetes_io_managed_by=\"Helm\", cmdline =~\".*grafana.*\"}[1d])) / (1000000 * 1000 * 24)",
     "legendFormat": "Grafana"
    },
    {
     "expr": "sum(sum_over_time(scaph_process_power_consumption_microwatts{app_kubernetes_io_managed_by=\"Helm\", cmdline =~\".*minio.*\"}[1d])) / (1000000 * 1000 * 24)",
     "legendFormat": "Minio"
    }
   ]
  },
  {
   "title": "KFP Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(scaph_process_power_consumption_microwatts{app_kubernetes_io_managed_by=\"Helm\", cmdline!~\".*(bin/|app/|conf/|--loglevelinfo|scaphandreprometheus--port8081).*\", exe!~\".*(containerd-shim|nginx|postgres|sleep|workflow-contro|pause|minio|grafana-server|systemd-journal|manager|etcd|kube-apiserver|kube-controller|kube-scheduler|local-path-prov|mysqld|node|persistence_age).*\"}) / 1000000"
    }
   ]
  },
  {
   "title": "Energy Consumption of KFP Components (1day)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(scaph_process_power_consumption_microwatts{app_kubernetes_io_managed_by=\"Helm\", cmdline=~\".*(pull_data_component|python3-mpipinstall--quiet--no-warn-script-locationpandas~=1.4.2numpyfolktableskfp==1.8.22).*\"}[1d])) / (1000000 * 1000 * 24)",
     "legendFormat": "Pull data"
    },
    {
     "expr": "sum(sum_over_time(scaph_process_power_consumption_microwatts{app_kubernetes_io_managed_by=\"Helm\", cmdline=~\".*(preprocess_component|python3-mpipinstall--quiet--no-warn-script-locationpandas~=1.4.2scikit-learn~=1.0.2numpykfp==1.8.22).*\"}[1d])) / (1000000 * 1000 * 24)",
     "legendFormat": "Preprocess"
    },
    {
     "expr": "sum(sum_over_time(scaph_process_power_consumption_microwatts{app_kubernetes_io_managed_by=\"Helm\", cmdline=~\".*(train_component|python3-mpipinstall--quiet--no-warn-script-locationnumpypandas~=1.4.2aif360scikit-learn~=1.0.2mlflow~=1.25.0boto3~=1.21.0kfp==1.8.22).*\"}[1d])) / (1000000 * 1000 * 24)",
     "legendFormat": "Train"
    },
    {
     "expr": "sum(sum_over_time(scaph_process_power_consumption_microwatts{app_kubernetes_io_managed_by=\"Helm\", cmdline=~\".*(evaluate_component|python3-mpipinstall--quiet--no-warn-script-locationnumpymlflow~=1.25.0prometheus_clientkfp==1.8.22).*\"}[1d])) / (1000000 * 1000 * 24)",
     "legendFormat": "Evaluate"
    },
    {
     "expr": "sum(sum_over_time(scaph_process_power_consumption_microwatts{app_kubernetes_io_managed_by=\"Helm\", cmdline=~\".*(deploy_model_component|python3-mpipinstall--quiet--no-warn-script-locationkservekfp==1.8.22).*\"}[1d])) / (1000000 * 1000 * 24)",
     "legendFormat": "Deploy"
    },
    {
     "expr": "sum(sum_over_time(scaph_process_power_consumption_microwatts{app_kubernetes_io_managed_by=\"Helm\", cmdline!~\".*(bin/|app/|conf/|--loglevelinfo|scaphandreprometheus--port8081|preprocess|pull_data|train|evaluate|deploy_model|numpy|python3-mpipinstall--quiet--no-warn-script-locationkservekfp==1.8.22|metadata|msklearnserver|python3server.py).*\", exe!~\".*(containerd-shim|nginx|postgres|sleep|workflow-contro|pause|minio|grafana-server|systemd-journal|manager|etcd|kube-apiserver|kube-controller|kube-scheduler|local-path-prov|mysqld|node|persistence_age).*\"}[1d])) / (1000000 * 1000 * 24) ",
     "legendFormat": "Inference"
    }
   ]
  }
 ]
}