{
 "title": "Evidently Numerical Target Drift Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "model_name", "label": "Model Name", "query": { "query": "label_values(model_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Rows Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "evidently:num_target_drift:count{model_name=\"${model_name:raw}\"}",
     "legendFormat": "{{dataset}}"
    }
   ]
  },
  {
   "title": "Drift Score (p-value)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "evidently:num_target_drift:drift{model_name=\"${model_name:raw}\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  }
 ]
}
{
 "title": "Evidently Data Drift Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "model_name", "query": { "query": "label_values(model_name)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Evidently Data Drift Monitoring\n\n  Here can be your information about dashboard and its usage.\n"
   }
  },
  { "title": "General information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Dataset Drift",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "evidently:data_drift:dataset_drift{model_name=\"${model_name:raw}\"}",
     "legendFormat": "dataset drift"
    }
   ]
  },
  {
   "title": "Share of drifted features",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "evidently:data_drift:share_drifted_features{model_name=\"${model_name:raw}\"}",
     "legendFormat": "share"
    }
   ]
  },
  {
   "title": "# of drifted features",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_drift:n_drifted_features{model_name=\"${model_name:raw}\"}",
     "legendFormat": "Drifted"
    }
   ]
  },
  {
   "title": "# of features",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_drift:n_drifted_features{model_name=\"${model_name:raw}\"} / evidently:data_drift:share_drifted_features{model_name=\"${model_name:raw}\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Detailed information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "P-value of features",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "evidently:data_drift:p_value{model_name=\"${model_name:raw}\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "evidently:reference_dataset_hash",
     "legendFormat": "reference_hash"
    }
   ]
  }
 ]
}
{
 "title": "Cluster Monitoring for Kubernetes",
 "description": "This dashboard provides cluster admins with the ability to monitor nodes and identify workload bottlenecks. It can be deployed with PSPs enabled using the following helm chart - https://github.com/pivotal-cf/charts-grafana",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage ($interval avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{id=\"/\"}) / sum (container_fs_limit_bytes{id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{id=\"/\"})"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pods CPU usage ($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Pods network I/O ($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  }
 ]
}