apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

configMapGenerator:
- name: storage-configmap
  envs:
    - config.env
  behavior: merge

secretGenerator:
- name: storage-secrets
  envs:
    - secret.env

resources: 
- storage-namespace.yaml
- structured_data/
- vector_data/
- graph_data/
- cache_data/
- object_data/
- relational_data/