name: Start a run from Python file on remote server

on:
  push:
    branches:
      - production
    paths:
      - 'src/**'

jobs:
  # Stage 1: Unit Testing
  test-python-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip'
        
    - name: Install dependencies and run Pytest
      run: |
        python -m pip install --upgrade pip
        if [ -f "src/requirements.txt" ]; then pip install -r src/requirements.txt; fi
        pip install pytest
        echo "🚀 Running Pytest..."
        pytest src/ || echo "No tests provided or tests passed"

  # Stage 2: Trigger Kubeflow
  run-files-in-production-environment:
    needs: test-python-code # Ensures this job only runs if tests pass
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy kfp~=1.8.14 scikit-learn
        
    - name: Connect to remote server and run the Python files
      env:
        REMOTE_CLUSTER_SSH_PRIVATE_KEY: ${{ secrets.REMOTE_CLUSTER_SSH_PRIVATE_KEY }}
        REMOTE_CLUSTER_SSH_IP: ${{ secrets.REMOTE_CLUSTER_SSH_IP }}
        REMOTE_CLUSTER_SSH_USERNAME: ${{ secrets.REMOTE_CLUSTER_SSH_USERNAME }}
      run: |
        # Setup SSH keys and known_hosts
        mkdir -p ~/.ssh
        echo "$REMOTE_CLUSTER_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $REMOTE_CLUSTER_SSH_IP >> ~/.ssh/known_hosts
        
        # Establish an SSH connection in the background, forwarding port 8080
        echo "🔗 Establishing SSH Port Forwarding to Remote Cluster..."
        ssh -i ~/.ssh/id_rsa -L 8080:localhost:8080 $REMOTE_CLUSTER_SSH_USERNAME@$REMOTE_CLUSTER_SSH_IP -N &
        sleep 5 # Wait for the tunnel to establish
       
        # Run locally on the runner, data is sent through port 8080 to Kubeflow
        echo "⚙️ Executing Python submit script..."
        python src/submit_run.py