name: Start a run from Jupyter Notebook on remote server

on:
  push:
    branches:
      - production
    paths:
      - 'notebooks/**'

jobs:
  # Stage 1: Unit Testing
  test-python-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Run Pytest
      run: |
        pip install pytest
        pytest src/ || echo "No tests provided or tests passed"

  # Stage 2: Trigger Kubeflow via Notebook
  run-notebook-in-production-environment:
    needs: test-python-code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter kfp~=1.8.14
        
    - name: Connect to remote server and run the Notebook
      env:
        REMOTE_CLUSTER_SSH_PRIVATE_KEY: ${{ secrets.REMOTE_CLUSTER_SSH_PRIVATE_KEY }}
        REMOTE_CLUSTER_SSH_IP: ${{ secrets.REMOTE_CLUSTER_SSH_IP }}
        REMOTE_CLUSTER_SSH_USERNAME: ${{ secrets.REMOTE_CLUSTER_SSH_USERNAME }}
      run: |
        mkdir -p ~/.ssh
        echo "$REMOTE_CLUSTER_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $REMOTE_CLUSTER_SSH_IP >> ~/.ssh/known_hosts
        
        # Establish an SSH Port Forwarding
        ssh -i ~/.ssh/id_rsa -L 8080:localhost:8080 $REMOTE_CLUSTER_SSH_USERNAME@$REMOTE_CLUSTER_SSH_IP -N &
        sleep 5
       
        # Execute the Jupyter Notebook locally
        echo "📓 Executing Jupyter Notebook..."
        jupyter nbconvert --execute --to notebook --inplace notebooks/demo-pipeline.ipynb

    - name: Upload executed Notebook as artifact
      uses: actions/upload-artifact@v4
      with:
        name: executed-production-notebook
        path: notebooks/demo-pipeline.ipynb
        retention-days: 7