# Required for deploy model to have the necessery permissions to create inference services

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kserve-deployer
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - secrets
      - serviceaccounts
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - persistentvolumes
      - persistentvolumeclaims
  - verbs:
      - create
      - delete
      - get
    apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
  - verbs:
      - get
      - list
      - watch
      - update
      - patch
    apiGroups:
      - argoproj.io
    resources:
      - workflows
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
      - pods/exec
      - pods/log
      - services
  - verbs:
      - '*'
    apiGroups:
      - ''
      - apps
      - extensions
    resources:
      - deployments
      - replicasets
  - verbs:
      - '*'
    apiGroups:
      - kubeflow.org
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - batch
    resources:
      - jobs
  - verbs:
      - '*'
    apiGroups:
      - machinelearning.seldon.io
    resources:
      - seldondeployments
  - verbs:
      - '*'
    apiGroups:
      - serving.kserve.io
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - networking.istio.io
    resources:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-runner-binding-cluster
  labels:
    application-crd-id: kubeflow-pipelines
subjects:
  - kind: ServiceAccount
    name: pipeline-runner
    namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kserve-deployer